# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 07:46
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='config',
            field=jsonfield.fields.JSONField(default=dict, help_text='configuration in NetJSON DeviceConfiguration format', verbose_name='configuration'),
        ),
    ]
